version: "3"
services:
    mssql:
        image: microsoft/mssql-server-linux
        ports:
            - "1433:1433"
        environment:
            # userName: sa
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
